# file: inventory.yml
proxmox:
  hosts:
    pve0[1:3]:

ntp_servers:
  hosts:
    sundial:
    
dns_server:
  hosts:
    monorail:

magic_kingdom:
  hosts:
    main-street-usa:
    tomorrowland:
    fantasyland:

prometheus_server:
  hosts:
    cinderella-castle:

prometheus_nodes:
  hosts:
    cinderella-castle:

# node_explorer:
#   hosts:
#     cinderella-castle:

# alertmanager:
#   hosts:
#     cinderella-castle:

# grafana:
#   hosts:
#     cinderella-castle:

papermc_server:
# ansible-galaxy role install engonzal.papermc
  hosts:
    arcade:

semaphore_server:
  hosts:
    imagineering:

n8n_server:
  hosts:
    tiki-room:

traefik_server:
  hosts:
    lightning_lane:

# dhcp_server:
#   hosts:
#     matchbox:

backup_servers:
  hosts:
    timekeeper:

# freeipa:
#   hosts:
#     infra01:

# ipaserver:
#   hosts:
#     infra01.int.mk-labs.cloud:

# matchbox_server:
#   hosts:
#     matchbox:

terraform_server:
  hosts:
    infra01:

hub_cluster:
  hosts:
    ocp-hub:

internal_cluster:
  hosts:
    int-master01:
    int-master02:
    int-master03:
#    int-worker01:
    int-worker02:

fastpass_control_plane:
  hosts:
    space-mountain:
    big-thunder-mountain:
    splash-mountain:

fastpass_workers:
  hosts:
    haunted-mansion: # backstage
    peter-pans-flight: # backstage

fastpass:
  children:
    fastpass_control_plane:
    fastpass_workers:

# sql_servers:
#   hosts:
#     sql01:

# docker_servers:
#   hosts:
#     docker01:

# observer:
#   hosts:
#     prometheus:

# target:
#   hosts:
#     prometheus: